UPDATE DONVI SET TRGDV = 'NV0756' WHERE MADV = 'CNTT';
UPDATE DONVI SET TRGDV = 'NV0757' WHERE MADV = 'DIENTU';
UPDATE DONVI SET TRGDV = 'NV0758' WHERE MADV = 'HOA';
UPDATE DONVI SET TRGDV = 'NV0759' WHERE MADV = 'LICHSU';
UPDATE DONVI SET TRGDV = 'NV0760' WHERE MADV = 'QUANTRI';
UPDATE DONVI SET TRGDV = 'NV0761' WHERE MADV = 'XAHOI';
UPDATE DONVI SET TRGDV = 'NV0762' WHERE MADV = 'PDT';
UPDATE DONVI SET TRGDV = 'NV0763' WHERE MADV = 'PKT';
UPDATE DONVI SET TRGDV = 'NV0764' WHERE MADV = 'TCHC';
UPDATE DONVI SET TRGDV = 'NV0765' WHERE MADV = 'CTSV';
UPDATE DONVI SET TRGDV = 'NV0766' WHERE MADV = 'MOITRUONG';
UPDATE DONVI SET TRGDV = 'NV0767' WHERE MADV = 'PLT';
UPDATE DONVI SET TRGDV = 'NV0768' WHERE MADV = 'BAOCHI';
UPDATE DONVI SET TRGDV = 'NV0769' WHERE MADV = 'TC-KT';
UPDATE DONVI SET TRGDV = 'NV0770' WHERE MADV = 'GIAODUC';

COMMIT;
