--SELECT * FROM DBA_REGISTRY WHERE COMP_NAME = 'Oracle Label Security';
--select name, status, description from dba_ols_status;
--SELECT NAME, OPEN_MODE FROM V$PDBS;
--SELECT NAME, PDB, CON_ID FROM V$ACTIVE_SERVICES WHERE PDB IS NOT NULL;
--SELECT NAME FROM V$ACTIVE_SERVICES WHERE NAME NOT LIKE 'SYS%' AND NAME != 'XE';
--SELECT NAME, CON_ID FROM V$ACTIVE_SERVICES;
--SELECT CON_ID, NAME FROM V$PDBS;


--ALTER SESSION SET CONTAINER=CDB$ROOT;


SELECT VALUE FROM v$option WHERE PARAMETER = 'Oracle Label Security';
SELECT STATUS FROM DBA_OLS_STATUS WHERE NAME = 'OLS_CONFIGURE_STATUS';

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

select * from v$services;

ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;


-- Mở và chuyển vào PDB để sử dụng
ALTER PLUGGABLE DATABASE PDB_QLDH OPEN READ WRITE;
ALTER SESSION SET CONTAINER=PDB_QLDH;
SHOW CON_NAME;

---> TẠO ADMIN OLS & CẤP QUYỀN CHO ADMIN_OLS
CREATE USER ADMIN_OLS IDENTIFIED BY 123 CONTAINER = CURRENT;
GRANT CREATE SESSION TO ADMIN_OLS WITH ADMIN OPTION;    
GRANT CONNECT,RESOURCE TO ADMIN_OLS; --CẤP QUYỀN CONNECT VÀ RESOURCE
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --CẤP QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --CẤP QUYỀN ĐỌC DICTIONARY
---> CẤP QUYỀN EXECUTE CHO ADMIN_OLS
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION;
---> ADD ADMIN_OLS VÀO LBAC_DBA
GRANT LBAC_DBA TO ADMIN_OLS;
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS; -- CẤP QUYỀN THỰC THI

GRANT CREATE USER TO ADMIN_OLS;
GRANT ALTER USER, DROP USER TO ADMIN_OLS;


--EXECUTE SA_SYSDBA.DROP_POLICY('OLS_QLDH');
-- TẠO CHÍNH SÁCH OLS (KHỞI ĐỘNG LẠI SQLDEV ĐỂ CẬP NHẬT OLS ENABLE)
BEGIN
    SA_SYSDBA.CREATE_POLICY(
    policy_name => 'OLS_QLDH',
    column_name => 'OLS_THONGBAO'
);
END;
/
--ENABLE POLICY VỪA TẠO -> KHOI DONG LẠI SQLDEV
EXEC SA_SYSDBA.ENABLE_POLICY('OLS_QLDH');


--TẠO COMPONENT CỦA LABEL
--->TẠO LEVEL
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDH',3000,'TDV','TRUONG_DON_VI');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDH',2000,'NV','NHAN_VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDH',1000,'SV','SINH_VIEN');
--->TẠO COMPARTMENT
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDH',10,'T','TOAN');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDH',20,'L','LY');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDH',30,'H','HOA');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDH',40,'HC','HANH_CHINH');
--->TẠO GROUP
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_QLDH',1,'CS1','CO_SO_1');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_QLDH',2,'CS2','CO_SO_2');




--B4: CONNECT SYS KIỂM TRA COMPONENT TẠO ĐÚNG CHƯA
SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY;


--DROP TABLE THONGBAO;
-- Tạo bảng
CREATE TABLE THONGBAO
(
    MATB INT PRIMARY KEY,
    NOIDUNG NVARCHAR2(100),
    DIADIEM NVARCHAR2(10)
);
-- Insert dữ liệu
INSERT INTO THONGBAO VALUES (1, N'Đây là thông báo cần phát tán đến tất cả trưởng đơn vị', NULL);
INSERT INTO THONGBAO VALUES (2, N'Đây là thông báo cần phát tán đến tất cả nhân viên', NULL);
INSERT INTO THONGBAO VALUES (3, N'Đây là thông báo cần phát tán đến tất cả sinh viên', NULL);
INSERT INTO THONGBAO VALUES (4, N'Đây là thông báo cần phát tán đến sinh viên thuộc khoa Hóa ở cơ sở 1', N'Cơ sở 1');
INSERT INTO THONGBAO VALUES (5, N'Đây là thông báo cần phát tán đến sinh viên thuộc khoa Hóa ở cơ sở 2', N'Cơ sở 2');
INSERT INTO THONGBAO VALUES (6, N'Đây là thông báo cần phát tán đến sinh viên thuộc khoa Hóa ở cả hai cơ sở', NULL);
INSERT INTO THONGBAO VALUES (7, N'Đây là thông báo cần phát tán đến tất cả sinh viên thuộc cả hai cơ sở', NULL);
INSERT INTO THONGBAO VALUES (8, N'Đây là thông báo cần phát tán đến trưởng khoa Hóa ở cơ sở 1', N'Cơ sở 1');
INSERT INTO THONGBAO VALUES (9, N'Đây là thông báo cần phát tán đến trưởng khoa Hóa ở cơ sở 1 và cơ sở 2', NULL);
COMMIT;
--select * from thongbao;

-- Tạo các nhãn cần thiết để gán cho các dòng dữ liệu
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 1000, 'TDV::');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 990, 'NV::');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 980, 'SV::');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 970, 'SV:H:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 960, 'SV:H:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 950, 'SV:H:CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 940, 'SV::CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 930, 'TDV:H:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDH', 920, 'TDV:H:CS1,CS2');


-- CẬP NHẬT NHÃN TRONG BẢNG
BEGIN
 SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
 POLICY_NAME => 'OLS_QLDH',
 SCHEMA_NAME => 'ADMIN_OLS',
 TABLE_NAME => 'THONGBAO',
 TABLE_OPTIONS => 'NO_CONTROL'
);
END;
/

-- TẠO NHÃN
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'TDV::') WHERE MATB = 1;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'NV::') WHERE MATB = 2;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'SV::') WHERE MATB = 3;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'SV:H:CS1') WHERE MATB = 4;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'SV:H:CS2') WHERE MATB = 5;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'SV:H:CS1,CS2') WHERE MATB = 6;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'SV::CS1,CS2') WHERE MATB = 7;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'TDV:H:CS1') WHERE MATB = 8;
UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH', 'TDV:H:CS1,CS2') WHERE MATB = 9;

--UPDATE ĐỂ KHỞI TẠO LABEL TRONG BẢNG OLS_KHACHHANG
--UPDATE THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLDH','SV');


--ÁP DỤNG OLS VÀO BẢNG
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_QLDH','ADMIN_OLS','THONGBAO');
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name => 'OLS_QLDH',
    schema_name => 'ADMIN_OLS',
    table_name => 'THONGBAO',
    table_options => 'READ_CONTROL',
    predicate => NULL
);
END;

--UPDATE BẢNG THONGBAO (ĐỂ GỌI UPDATE LABEL)
--UPDATE THONGBAO SET NOIDUNG = NOIDUNG;


--DROP USER TDV001;
--DROP USER TDV002;
--DROP USER TDV003;
--DROP USER NV001;
--DROP USER SV001;
--DROP USER TDV004;
--DROP USER NV002;
--DROP USER NV003;

-- Tạo người dùng
CREATE USER TDV001 IDENTIFIED BY TDV001; -- Trưởng đơn vị có thể đọc được toàn bộ thông báo
CREATE USER TDV002 IDENTIFIED BY TDV002; -- Trưởng đơn vị phụ trách khoa Hóa tại cơ sở 2
CREATE USER TDV003 IDENTIFIED BY TDV003; -- Trưởng đơn vị phụ trách khoa Lý tại cơ sở 2
CREATE USER NV001 IDENTIFIED BY NV001; -- Nhân viên thuộc khoa Hóa tại cơ sở 2
CREATE USER SV001 IDENTIFIED BY SV001; -- Sinh viên khoa Hóa tại cơ sở 2
CREATE USER TDV004 IDENTIFIED BY TDV004; -- Trưởng đơn vị có thể đọc được các thông báo về Hành chính
CREATE USER NV002 IDENTIFIED BY NV002; -- Nhân viên có thể đọc toàn bộ thông báo dành cho tất cả nhân viên
CREATE USER NV003 IDENTIFIED BY NV003; -- Nhân viên có thể đọc thông báo về Hành chính tại cơ sở 1

-- Cấp quyền kết nối
GRANT CONNECT TO TDV001;
GRANT CONNECT TO TDV002;
GRANT CONNECT TO TDV003;
GRANT CONNECT TO NV001;
GRANT CONNECT TO TDV001;
GRANT CONNECT TO SV001;
GRANT CONNECT TO TDV004;
GRANT CONNECT TO NV002;
GRANT CONNECT TO NV003;

-- Cấp quyền xem trên bảng THONGBAO
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TDV001;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TDV002;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TDV003;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO NV001;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TDV001;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO SV001;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TDV004;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO NV002;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO NV003;

-- Gán nhãn bảo mật cho từng người dùng
BEGIN
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','TDV001','TDV:T,L,H,HC:CS1,CS2');
END;
-- Gán nhãn bảo mật cho từng người dùng
BEGIN
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','SV001','SV:H:CS2');
END;
/


BEGIN
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','TDV001','TDV:T,L,H,HC:CS1,CS2'); -- Trưởng đơn vị có thể đọc được toàn bộ thông báo
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','TDV002','TDV:H:CS2'); -- Trưởng đơn vị phụ trách khoa Hóa tại cơ sở 2
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','TDV003','TDV:L:CS2'); -- Trưởng đơn vị phụ trách khoa Lý tại cơ sở 2
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','NV001','NV:H:CS2'); -- Nhân viên thuộc khoa Hóa tại cơ sở 2
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','SV001','SV:H:CS2'); -- Sinh viên khoa Hóa tại cơ sở 2
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','TDV004','TDV:HC:CS1,CS2'); -- Trưởng đơn vị có thể đọc được các thông báo về Hành chính
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','NV002','NV:T,L,H,HC:CS1,CS2'); -- Nhân viên có thể đọc toàn bộ thông báo dành cho tất cả nhân viên
SA_USER_ADMIN.SET_USER_LABELS('OLS_QLDH','NV003','NV:HC:CS1'); -- Nhân viên có thể đọc thông báo về Hành chính tại cơ sở 1
END;
/

--BEGIN
--SA_USER_ADMIN.SET_USER_LABELS(
--    POLICY_NAME => 'OLS_QLDH',
--    USER_NAME   => 'TDV001',
--    MAX_READ_LABEL  => 'TDV:T,L,H,HC:CS1,CS2',
--    MAX_WRITE_LABEL => 'TDV:T,L,H,HC:CS1,CS2'
--);
--END;

/*
SELECT * FROM DBA_SA_POLICIES WHERE POLICY_NAME = 'OLS_QLDH';
SELECT * FROM THONGBAO;
SELECT MATB, LABEL_TO_CHAR(OLS_THONGBAO) FROM ADMIN_OLS.THONGBAO;
SELECT * FROM DBA_SA_USER_LABELS WHERE USER_NAME = 'TD001';
SELECT * FROM DBA_TAB_PRIVS WHERE TABLE_NAME = 'THONGBAO' AND GRANTEE = 'TD001';
-- Kiểm Tra Quyền Truy Cập của Người Dùng
--SELECT * FROM DBA_SA_USERS WHERE POLICY_NAME = 'SEC_POLICY';
SELECT * FROM DBA_SA_LABELS WHERE POLICY_NAME = 'OLS_QLDH';
--SELECT * FROM ADMIN_OLS.THONGBAO;
*/